spring.application.name=spring-security

#data-base:
spring.datasource.url=jdbc:mysql://localhost:3306/spring_security
spring.datasource.username=root
spring.datasource.password=root

#data-source:


